[[libsemigroups]]
arch = "aarch64"
git-tree-sha1 = "f9dca209a226caf2f03e4a6c2d58c08ad7c43472"
os = "macos"

    [[libsemigroups.download]]
    sha256 = "850e6ec2fa8d04038d417b82b14f7e116b596b02a9800b1cb1951cea1ae88edc"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.aarch64-apple-darwin.tar.gz"
[[libsemigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e585a10aeef475fa394c0288ff3e00aed0bd61e0"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "9afa77a8119265cdc2d9e0a519feb52601abcc408404042e0a25f0839e07ce01"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17d83797594ea8b61efe3414e7cd311746836287"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "e974a12804b3b0079c75a5b843619716057a3006251c902becca7b0569373570"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "aarch64"
git-tree-sha1 = "1e42e9be5fb46fdebfbad8813d256b4fd499d93a"
os = "freebsd"

    [[libsemigroups.download]]
    sha256 = "f6ebd54bb2d56ffa174878bec0a151f37130c04f4d2e63190259e89c755100c9"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.aarch64-unknown-freebsd.tar.gz"
[[libsemigroups]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1523d1e70877d0cfa8b52af29cccaf014feb30e9"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "0194ae5790d7fa671cfdb72f408f84cd87b991630e5abf820ab798901b1c754c"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b78668253aa31b54b93066252a1340a2589983a"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "1decde5eca0b15394e5f53f8fae42674463fcdd80c1334a3a32720d5ed5c3930"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a01a8881d9d9a0abe50ad011cfad0473372a939"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "83107b8f62d511032076c08e38d8ac8f12f6b4a5c30da39c9fd287463decf03d"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f95c0d102d3843d8738e33556166e55ab880faa"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "82692b2b38d9e8e91664291adcefd2f959176defa05bbf7aed030eff5574e790"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45ad10beba8a4e46a3dfb5d5fd386249490b0d7d"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "ad6d1e64b0378e9a535aed03624348c335805ce102660f9c2935a89e34331520"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.i686-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75abce9e6a2f72a5f91a144b9e192622b4739e13"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "f881dbe047bab893e727daa2a83f82bb854cc63d7ab211c7ccff83afc325d862"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.i686-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c70f30529bcb929d3ac6cda0945d2a28e0ba7d3a"
os = "windows"

    [[libsemigroups.download]]
    sha256 = "1bdc788658da8e11756a890886fceb6f2207fd7f8e8db2f9c051ddb8b998f3d3"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.i686-w64-mingw32-cxx11.tar.gz"
[[libsemigroups]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "524f90dee06c293bc2fca6e8a38f15e97ad6c642"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "1b3e4e4b0c28512c6147e9240c57ba4afffc50af560c2776c71d99236b3627d5"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2a071504b61a2ec9c71587537089cd8cef24f7e"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "3ad9c35227b2e4fc3ae548b42b8881fa2253bf3c1c3feea949ac6db14e07ffea"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.riscv64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
git-tree-sha1 = "edf6515d82500ce0b0534c5ea10d42addc150885"
os = "macos"

    [[libsemigroups.download]]
    sha256 = "378f1d625b259740d25b9ce87471dd9c4622916d4f1f16c1aae936d5477961df"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.x86_64-apple-darwin.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74bf44a572eeae0bdf9aeb7a0bced2abbc5f59b9"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "20bd596daa792079c765be5c4e6f9eb63b82da8994e4e5c9574e360e2693dd36"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4000bdc47b0680ac1f709922b2dc449c1c2208fe"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "d1688ef72d3b3a9c84f2f263125573bd578a5b550af8253f79178a4f1653cb61"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
git-tree-sha1 = "78c7d149d949c75df704c03e28297aec0ba65e32"
os = "freebsd"

    [[libsemigroups.download]]
    sha256 = "3fcc7af81c4fbb6d65b372e67b95279162fda7470a18e631ec02ed407ecccf1d"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.x86_64-unknown-freebsd.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af06cd4f227ec39e0d625955a93ac18da8906bc8"
os = "windows"

    [[libsemigroups.download]]
    sha256 = "603c35fde2b2c15acda1b726a86915f65333217f9128a6b49848e2faba83d587"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.4+0/libsemigroups.v3.5.4.x86_64-w64-mingw32-cxx11.tar.gz"
