[[libsemigroups]]
arch = "aarch64"
git-tree-sha1 = "5a97c36d48c5171f077af7ff0a40a70fa55af46c"
os = "macos"

    [[libsemigroups.download]]
    sha256 = "4315c39319273af08fcf20fa8f04fc5125466144e118e16c7062162caf2568d5"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.aarch64-apple-darwin.tar.gz"
[[libsemigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbe97a48054677f1d35f1bf8097ae1e5901076ab"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "eaa1371798c3a9b09b5c9cfcf7c170b1c331c996fb88caf2384ba247b88b4b8f"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed9fdc82315e066b5dc2a8dedc8fa88b620ef799"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "5e1b9b032ca595cb2025e5ea7ae179713e7c72e73e91ac3df422492f4f664157"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "aarch64"
git-tree-sha1 = "61e0460d6129ce9149159b7fddac87c04f4ab4e8"
os = "freebsd"

    [[libsemigroups.download]]
    sha256 = "caa5bb2e659adc7c0d9b4ba02e5de98f7bcdfcb23da117554a170013de5fe712"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.aarch64-unknown-freebsd.tar.gz"
[[libsemigroups]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61944f383866ecb18fdd547a398b41bd14f0e45f"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "2057329eea4f653b88bac77428e4e71abcfbcfca5d49a329fa118f77263ff55a"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "953d2323b515c2f878e0b9b1a51b7bb6c9573a0c"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "f610d1f666ef5064d6f3a1ba5d804b54a6d8769cd660567d7a7c9a4a1fa2a303"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5570b62a70914506592368e0dfc3b4f43043ac9"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "9c56b0cd6546608462f256f7656232d55f9341853eb59a04a46c591af31f4aca"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5beba476e33a6d344eb1fa9d71ec0e7916aa71ec"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "27438f3a228bd8404a79796d63b425a3b461ff281dcb339c38ec1e30327519a9"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d8c85e774cc23b52c51b9aa8ba7625a708b56eb"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "5b791593f6215090e2252d195e15d0972b6794c2572df5c900d62702ac3e08fc"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.i686-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a7a77496c70591717a28ab17f3475362b6b5aa3"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "6cbccde5eb2e59758a01ddf7440adec0c73076b8adbb67fc5594650473819e81"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.i686-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad2aff172435248e6c1aa7b57ef90f1649c33f94"
os = "windows"

    [[libsemigroups.download]]
    sha256 = "1ec6748fb7e434b62c78d3567a3a91691c16a4636a85398267081a97487c1d85"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[libsemigroups]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1470607a19f7d1c992a464583a443313db23a9e5"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "29848f77dbaf790b6a40fdd45b1f8fff1e1dd45a510ae4489293a72b29f7042d"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68c592739caf081f45d6216b0487c58630406569"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "f6723e38efcc360914ef46d04f04e893d6801d92f53de1d9097b172efed1deb9"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.riscv64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
git-tree-sha1 = "dd4994aaa0b5b367d4fcf10c8300cec99d1877db"
os = "macos"

    [[libsemigroups.download]]
    sha256 = "bc0097c4d8f7e1956f4ae45b0baf171ec9100817b42fa68ecca53f91546c15f5"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.x86_64-apple-darwin.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2202d4c1bc847e567a7297e0c33c0882a7c72bc"
libc = "glibc"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "fb9cd13f24a561a0e553441358c9fb190dd5b59362c4a3b960cbcfd1c45a690b"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abac4330e5f9ebe19d6fffe0068bb53331e8ad14"
libc = "musl"
os = "linux"

    [[libsemigroups.download]]
    sha256 = "f40cecf057172831406d9498e00aac79a6555f194f4f4decdb5805e66db7f3d8"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[libsemigroups]]
arch = "x86_64"
git-tree-sha1 = "1fc5d9ca6ff9908efee0f211d03f10109c02e516"
os = "freebsd"

    [[libsemigroups.download]]
    sha256 = "2c6204667e9f75207e7beaa15fceba49810f043596b7f42537f0541c47a7a139"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.x86_64-unknown-freebsd.tar.gz"
[[libsemigroups]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e784758d95eb8aa137844e9bd8fd7dcca81f81f0"
os = "windows"

    [[libsemigroups.download]]
    sha256 = "17942149433c42442a041113b2a2ab99e9d6e07dccb3e9ac8d204f3de9417456"
    url = "https://github.com/JuliaBinaryWrappers/libsemigroups_jll.jl/releases/download/libsemigroups-v3.5.1+1/libsemigroups.v3.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
