# Autogenerated wrapper script for libsemigroups_jll for aarch64-apple-darwin
export libsemigroups

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libsemigroups")
JLLWrappers.@declare_library_product(libsemigroups, "@rpath/libsemigroups.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsemigroups,
        "lib/libsemigroups.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
