# Autogenerated wrapper script for libsemigroups_jll for armv7l-linux-musleabihf-cxx11
export libsemigroups

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libsemigroups")
JLLWrappers.@declare_library_product(libsemigroups, "libsemigroups.so.3")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsemigroups,
        "lib/libsemigroups.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
