# Autogenerated wrapper script for libsemigroups_jll for x86_64-w64-mingw32-cxx11
export libsemigroups

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libsemigroups")
JLLWrappers.@declare_library_product(libsemigroups, "libsemigroups-3.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsemigroups,
        "bin\\libsemigroups-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
